### ISSUE TITLE
Replace `name_as_*` and `value_as_*` methods on `Node` with `TryInto` impl

### ISSUE THREAD

**Issue by stoically** [stoically/syn-rsx#16]
Keep the methods on the `Node` but mark them deprecated.

**Comment by stoically** [comment]
This actually doesn't work since `Node::name/value` are options. I still feel like the API could use some improvement, just not sure how. Open to suggestions.

**Comment by Zizico2** [comment]
My suggestion here would be to do handle it like `syn` does. Have an `Enum` with the possible variants and a correspondent `struct` for every one.

**Comment by Zizico2** [comment]
This may be my least favourite thing about `syn-rsx`. The API doesn't feel very rusty. I just end up unwraping a lot. And then back tracking and discovering where the unwraps can and cannot fail.

**Comment by Zizico2** [comment]
> This actually doesn't work since `Node::name/value` are options. I still feel like the API could use some improvement, just not sure how. Open to suggestions.

It would still work, no? We can always `.map` the options. Would not be as clean as a single `try_into`, but it would be more idiomatic then the current solution. I still prefer my suggestion above though.

**Comment by stoically** [comment]
> The API doesn't feel very rusty.

I'd agree.

> My suggestion here would be to do handle it like syn does. Have an Enum with the possible variants and a correspondent struct for every one.

If I understand that right that's a suggestion regarding the node children, right? So, basically something like

```rust
enum Node {
  Element(NodeElement),
  Attribute(NodeAttribute),
  ...
}
```

I was considering this when implementing. The reason I decided against it was: All nodes basically share the same fields, so I would end up duplicating the same node for every type of node, with only slight adjustments. And since the type of the node is available via `Node::node_type` currently, it felt like that's enough of a context information to work with the node when traversing. I'm however open to rethink that decision and would be interested to look a suggestion that doesn't require duplicating things too much.

Also not exactly sure how it'd help in terms of `TryInto<T>` implementations, as those would still need to implemented for the node `value` and `type` specifically, unless I'm missing something?

> My suggestion here would be to do handle it like syn does. Have an Enum with the possible variants and a correspondent struct for every one.

Right, I could implement `TryInto` on `NodeName` either way, good point, will do that. For `Node::value` I'd have to do https://github.com/stoically/syn-rsx/issues/15 first, but I guess that's a good reason to finally do it.

**Comment by stoically** [comment]
> I just end up unwraping a lot. And then back tracking and discovering where the unwraps can and cannot fail.

That's a strong argument to live with less DRY code tho, since needing to depend on manually understanding the docs to do safe `unwrap`ing seems almost not type safe.

**Comment by stoically** [comment]
Started to look into an enum style `Node` implementation, and it actually isn't that bad in terms of duplication: https://github.com/stoically/syn-rsx/blob/3a42db12a3a135bd3dc061a4762f0c0af3a1e6af/src/node_enum.rs. Seems much cleaner.

**Comment by Zizico2** [comment]
Let me know if I can help. I agree with everything you said. And about the duplication part, I'm not that familiar with `syn-rsx`'s internals.
