### ISSUE TITLE
Node method to get span for node value

### ISSUE THREAD

**Issue by stoically** [stoically/syn-rsx#4]
This probably requires a huge pattern match covering all `syn::Expr`

**Comment by ZetaNumbers** [comment]
IIUC this issue is about getting span for any `NodeType` possible for a whole node. Right now my code implements this with names' or values' span. However there is no way to specify a span for an empty fragment node other than something like `Span::call_site()`. Correct me if I am wrong.

**Comment by stoically** [comment]
The idea for this issue was to get the span just for the value, which wouldn't work for nodes that don't have a value, like fragments.

Having a method for the whole node is a good idea, opened https://github.com/stoically/syn-rsx/issues/14 to track that.

**Comment by stoically** [comment]
Getting the span for a node value is actually already possible by just calling the [`span` method on the `Expr`](https://docs.rs/syn/latest/syn/enum.Expr.html#method.span).
